<?xml version="1.0" encoding="utf-8"?><Database Name="bakersdozen132" Class="bd13DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sqlserver8.loosefoot.com;Initial Catalog=bakersdozen132;Persist Security Info=True;User ID=ihdavis2" SettingsObjectName="ianhd.data.Properties.Settings" SettingsPropertyName="bakersdozen132ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="ihdavis.Link" Member="Links">
    <Type Name="Link">
      <Column Name="LinkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DestinationUrl" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveInd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis2.SiteProvider" Member="SiteProviders">
    <Type Name="SiteProvider">
      <Column Name="SiteProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteCd" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientId" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ClientSecret" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Provider_SiteProvider" Member="Provider" ThisKey="ProviderId" OtherKey="ProviderId" Type="Provider" IsForeignKey="true" />
      <Association Name="Site_SiteProvider" Member="Site" ThisKey="SiteCd" OtherKey="SiteCd" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.List" Member="Lists">
    <Type Name="List">
      <Column Name="ListId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateTouched" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastTouch" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="List_ListItem" Member="ListItems" ThisKey="ListId" OtherKey="ListId" Type="ListItem" />
      <Association Name="User_List" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.ListItem" Member="ListItems">
    <Type Name="ListItem">
      <Column Name="ListItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Checked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateTouched" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastTouch" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="List_ListItem" Member="List" ThisKey="ListId" OtherKey="ListId" Type="List" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.MovieReview" Member="MovieReviews">
    <Type Name="MovieReview">
      <Column Name="MovieId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailPosterUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ProfilePosterUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DetailedPosterUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Review" Type="System.String" DbType="NVarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="ReviewClass" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ReviewUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="ihdavis.SharedLink" Member="SharedLinks">
    <Type Name="SharedLink">
      <Column Name="SharedLinkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LinkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SharedWithUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SharedWithInviteeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SharedLinkStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SharedLinkStatus_SharedLink" Member="SharedLinkStatus" ThisKey="SharedLinkStatusId" OtherKey="SharedLinkStatusId" Type="SharedLinkStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.SharedLinkStatus" Member="SharedLinkStatus">
    <Type Name="SharedLinkStatus">
      <Column Name="SharedLinkStatusId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SharedLinkStatus_SharedLink" Member="SharedLinks" ThisKey="SharedLinkStatusId" OtherKey="SharedLinkStatusId" Type="SharedLink" />
    </Type>
  </Table>
  <Table Name="ihdavis.SiteUpdate" Member="SiteUpdates">
    <Type Name="SiteUpdate">
      <Column Name="SiteUpdateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteCD" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveInd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis.test" Member="tests">
    <Type Name="test">
      <Column Name="NullableInt" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ihdavis.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FacebookUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminInd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_List" Member="Lists" ThisKey="UserId" OtherKey="UserId" Type="List" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="UserId" OtherKey="UserId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="ihdavis.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis2.AdHoc" Member="AdHocs">
    <Type Name="AdHoc">
      <Column Name="AdHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis2.FeatureCategory" Member="FeatureCategories">
    <Type Name="FeatureCategory">
      <Column Name="FeatureCategoryCd" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ValueType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxValueLength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="FeatureCategory_SiteFeatureCategory" Member="SiteFeatureCategories" ThisKey="FeatureCategoryCd" OtherKey="FeatureCategoryCd" Type="SiteFeatureCategory" />
    </Type>
  </Table>
  <Table Name="ihdavis2.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="LogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogType" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ihdavis2.MovieReviewSeeItBlackList" Member="MovieReviewSeeItBlackLists">
    <Type Name="MovieReviewSeeItBlackList">
      <Column Name="MovieId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis2.MovieReviewSeeItWhiteList" Member="MovieReviewSeeItWhiteLists">
    <Type Name="MovieReviewSeeItWhiteList">
      <Column Name="MovieId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis2.PlayOrder" Member="PlayOrders">
    <Type Name="PlayOrder">
      <Column Name="PlayOrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CoupleTicketCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndividualTicketCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Seated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Thanked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HowDidYouHear" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UserAgent" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Platform" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReminderSent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="ihdavis2.Provider" Member="Providers">
    <Type Name="Provider">
      <Column Name="ProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RedirectUri" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CodeEndpoint" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CodeEndpointFormat" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccessTokenEndpoint" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccessTokenEndpointFormat" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccessTokenEndpointMethod" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="UserEndpoint" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Scope" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Provider_SiteProvider" Member="SiteProviders" ThisKey="ProviderId" OtherKey="ProviderId" Type="SiteProvider" />
    </Type>
  </Table>
  <Table Name="ihdavis2.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="SiteCd" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Domain" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Site_SiteProvider" Member="SiteProviders" ThisKey="SiteCd" OtherKey="SiteCd" Type="SiteProvider" />
      <Association Name="Site_SiteFeatureCategory" Member="SiteFeatureCategories" ThisKey="SiteCd" OtherKey="SiteCd" Type="SiteFeatureCategory" />
    </Type>
  </Table>
  <Table Name="ihdavis2.SiteFeature" Member="SiteFeatures">
    <Type Name="SiteFeature">
      <Column Name="SiteFeatureId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteFeatureCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Archive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SiteFeatureCategory_SiteFeature" Member="SiteFeatureCategory" ThisKey="SiteFeatureCategoryId" OtherKey="SiteFeatureCategoryId" Type="SiteFeatureCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ihdavis2.SiteFeatureCategory" Member="SiteFeatureCategories">
    <Type Name="SiteFeatureCategory">
      <Column Name="SiteFeatureCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteCd" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FeatureCategoryCd" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SiteFeatureCategory_SiteFeature" Member="SiteFeatures" ThisKey="SiteFeatureCategoryId" OtherKey="SiteFeatureCategoryId" Type="SiteFeature" />
      <Association Name="FeatureCategory_SiteFeatureCategory" Member="FeatureCategory" ThisKey="FeatureCategoryCd" OtherKey="FeatureCategoryCd" Type="FeatureCategory" IsForeignKey="true" />
      <Association Name="Site_SiteFeatureCategory" Member="Site" ThisKey="SiteCd" OtherKey="SiteCd" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
</Database>