<?xml version="1.0" encoding="utf-8"?><Database Name="bakersdozen132" Class="PlayDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sqlserver8.loosefoot.com;Initial Catalog=bakersdozen132;Persist Security Info=True;User ID=ihdavis2" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bakersdozen132ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="ihdavis2.PlayOrder" Member="PlayOrders">
    <Type Name="PlayOrder">
      <Column Name="PlayOrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CoupleTicketCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndividualTicketCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>